#!/usr/bin/env php
<?php

use WPSPCORE\App\App\Application;

define('WPSP_ARTISAN_START', microtime(true));


/**
 * ---
 * Autoload.
 */
if (file_exists(__DIR__ . '/vendor/autoload.php')) {
	require __DIR__ . '/vendor/autoload.php';
}

/**
 * ---
 * Xử lý command line.
 */
$app = new Application(__DIR__, 'WPSP Artisan', '1.0.0');

exit($app->run($argv));
