#!/usr/bin/env php
<?php

use WPSPLITE\App\Widen\Integrations\Integration;
use WPSPLITE\App\Widen\Routes\RouteManager;
use WPSPLITE\Routes\Actions;
use WPSPLITE\Routes\AdminBarMenus;
use WPSPLITE\Routes\AdminPages;
use WPSPLITE\Routes\Ajaxs;
use WPSPLITE\Routes\Apis;
use WPSPLITE\Routes\Blocks;
use WPSPLITE\Routes\CommentColumns;
use WPSPLITE\Routes\Customizers;
use WPSPLITE\Routes\DashboardWidgets;
use WPSPLITE\Routes\Filters;
use WPSPLITE\Routes\FrontPages;
use WPSPLITE\Routes\MediaColumns;
use WPSPLITE\Routes\MetaBoxes;
use WPSPLITE\Routes\NavLocations;
use WPSPLITE\Routes\PluginColumns;
use WPSPLITE\Routes\PostTypeColumns;
use WPSPLITE\Routes\PostTypes;
use WPSPLITE\Routes\RewriteFrontPages;
use WPSPLITE\Routes\Schedules;
use WPSPLITE\Routes\Shortcodes;
use WPSPLITE\Routes\Taxonomies;
use WPSPLITE\Routes\TaxonomyColumns;
use WPSPLITE\Routes\ThemeTemplates;
use WPSPLITE\Routes\UserColumns;
use WPSPLITE\Routes\UserMetaBoxes;
use WPSPLITE\Routes\Widgets;
use WPSPLITE\Routes\WPRoles;
use WPSPLITE\WPSP;

define('WPSPLITE_LITE_ARTISAN_START', microtime(true));

require_once __DIR__ . '/ArtisanHelpers.php';

$ensureDBConnect = ensureDBConnect();

if ($ensureDBConnect) {
	if (file_exists(__DIR__ . '/../../../wp-load.php')) {
		try {
			require_once __DIR__ . '/../../../wp-load.php';

			if (function_exists('is_plugin_active')) {
				/**
				 * Kiểm tra plugin đã được kích hoạt hay chưa.\
				 * Khi plugin đã được kích hoạt và hoạt động thành công\
				 * thì "artisan" (hay môi trường terminal) sẽ hoạt động với:
				 * - Full tính năng của WordPress.
				 * - Full tính năng của tất cả plugin đang hoạt động.
				 * - Full tính năng của plugin này.
				 */
				$pluginDir     = plugin_dir_path(__FILE__);
				$pluginDirName = plugin_basename($pluginDir);

				if (is_plugin_active($pluginDirName . '/main.php')) {
					define('WPSPLITE_LITE_ACTIVE', true);
				}
				else {
					echo "------------------------------------\n";
					echo "\033[32m[✓] You are running \"artisan\" in a WordPress environment!\033[0m\n";
					echo "\033[33m[!] Please activate the plugin to use the full features of \"artisan\"!\033[0m\n";
					echo "------------------------------------\n";
				}
			}
			else {
				echo "------------------------------------\n";
				echo "\033[31m[X] You are running \"artisan\" in a non-WordPress environment!\033[0m\n";
				echo "\033[31m[X] You may not be able to use all the features of \"artisan\"!\033[0m\n";
				echo "\033[33m[!] Please activate the plugin to use the full features of \"artisan\"!\033[0m\n";
				echo "------------------------------------\n";
			}
		}
		catch (\Throwable $e) {
			echo "------------------------------------\n";
			echo "\033[31m[X] You are running \"artisan\" in a non-WordPress environment!\033[0m\n";
			echo "\033[31m[X] You may not be able to use all the features of \"artisan\"!\033[0m\n";
			echo "\033[33m[!] Please activate the plugin to use the full features of \"artisan\"!\033[0m\n";
			echo "------------------------------------\n";
		}
	}
	else {
		echo "------------------------------------\n";
		echo "\033[31m[X] You are running \"artisan\" in a non-WordPress environment!\033[0m\n";
		echo "\033[31m[X] You may not be able to use all the features of \"artisan\"!\033[0m\n";
		echo "\033[33m[!] Please activate the plugin to use the full features of \"artisan\"!\033[0m\n";
		echo "------------------------------------\n";
	}
}
else {
	echo "------------------------------------\n";
	echo "\033[31m[X] You are running \"artisan\" in a non-WordPress environment!\033[0m\n";
	echo "\033[31m[X] You may not be able to use all the features of \"artisan\"!\033[0m\n";
	echo "\033[33m[!] Please connect to the database and activate the plugin to use the full features of \"artisan\"!\033[0m\n";
	echo "------------------------------------\n";
}

require __DIR__ . '/vendor/autoload.php';

$wpsp = WPSP::startConsole();

Integration::instance()->register();

if (defined('WPSPLITE_ACTIVE') && WPSPLITE_ACTIVE) {
	foreach ([
		AdminPages::class,
		Apis::class,
		Ajaxs::class,
		FrontPages::class,
		RewriteFrontPages::class,

		AdminBarMenus::class,
		Blocks::class,
		CommentColumns::class,
		Customizers::class,
		DashboardWidgets::class,
		MediaColumns::class,
		MetaBoxes::class,
		NavLocations::class,
		PluginColumns::class,
		PostTypeColumns::class,
		PostTypes::class,
		Schedules::class,
		Shortcodes::class,
		Taxonomies::class,
		TaxonomyColumns::class,
		ThemeTemplates::class,
		UserColumns::class,
		UserMetaBoxes::class,
		Widgets::class,
		WPRoles::class,

		Actions::class,
		Filters::class,
	] as $route) {
		(new $route())->register();
	}
}

RouteManager::instance()->executeAllRoutes(['Widgets']);
RouteManager::instance()->executeRouteByTypes(['Widgets']);

$app = $wpsp->getApplication();
$status = $app->handleCommand($argv);
exit($status);